### ISSUE TITLE
error message on library clpr

### ISSUE THREAD

**Issue by friguzzi** [SWI-Prolog/swish#100]
When writing a program using library clpr
https://swish.swi-prolog.org/p/clpr.pl
I get 
:- use_module(library(clpr)).
highlighted and hovering says that the library does not resolve any dependency
but the library is loaded as the query
{2.0=A*B}.
works. Remove the use_module commands swish says  {A} is undefined

**Comment by JanWielemaker** [comment]
The cross-referencer only looks at the program, not at the query.  Extended the example to illustrate this.
In general, cross-referencing between query and program is still problematic.

**Comment by friguzzi** [comment]
Sorry, I misinterpreted the message, I thought it meant that it could not find the library, not that predicates in the library were not used in the program.
