### ISSUE TITLE
temporary modules not clearing

### ISSUE THREAD

**Issue by friguzzi** [SWI-Prolog/swish#102]
In some cases, the temporary modules are not destroyed. I can see stuff that was asserted there even after the query has died, e.g., after a query has finished, I get from the console:
```
?- listing(example).
:- dynamic'3dd862cb-361a-421b-f7a0-2e44fd0ded0b':example/3.

'3dd862cb-361a-421b-f7a0-2e44fd0ded0b':example(0, uspec, aleph_false).
'3dd862cb-361a-421b-f7a0-2e44fd0ded0b':example(1, pos, []).
'3dd862cb-361a-421b-f7a0-2e44fd0ded0b':example(1, neg, []).

true.
```
Unfortunately I could not reproduce the behavior, it happened to me sometimes but I could not understand what triggers it. Most of the times temporary modules are distroyed. 
Jan, were you aware of this?

**Comment by JanWielemaker** [comment]
Is pretty much fixed for some time.
