### ISSUE TITLE
Swish is down (504 Gateway Time-out)

### ISSUE THREAD

**Issue by perryprog** [SWI-Prolog/swish#114]
Since the post of Swish on HN, [the website](https://swish.swi-prolog.org/) has been offline. Loading causes a 504 Gateway Time-out. It has been like this for several days now.

Apologizes if this isn't a great place to raise this issue.

**Comment by perryprog** [comment]
Appears resolved.

**Comment by perryprog** [comment]
It's down again. Same issue.

**Comment by JanWielemaker** [comment]
Restarted.  Will come with a more robust solution in a couple of weeks.  Sorry.
