### ISSUE TITLE
doc request: make doc more precise

### ISSUE THREAD

**Issue by Birdi7** [SWI-Prolog/swish#123]
Hello. 

Currently, the [page](https://github.com/SWI-Prolog/swish#running-swish-without-sandbox-limitations) about `Running SWISH without sandbox limitations` has a lack of precision: there are commands which depends on the current working directory, but there is no word about it. 

Example: in that chapter, we asked to create a `config-enabled` and make a soft link to a file with the config. But, there is nothing about the folder, in which we should create the `config-enabled`. There are no words about if we should restart the service for changes to apply or not. You used **relative** paths but **didn't specify the current directory** to run them.

As a result, I spend 3 hours figuring out how to start swish without sandbox, but I still have no idea how to make this happens.

**Comment by JanWielemaker** [comment]
Sorry to hear that.  I've updated the README.md in config-available a bit.  See https://github.com/SWI-Prolog/swish/tree/master/config-available/README.md.  Hope it helps.

**Comment by Birdi7** [comment]
Thank you a lot! Sorry if my words looked offensive. Sleep deprivation has its impact.
