### ISSUE TITLE
use_module(library(clpfd)) broken

### ISSUE THREAD

**Issue by Anniepoo** [SWI-Prolog/swish#129]
1. Visit https://swish.swi-prolog.org/example/clpfd_queens.pl
2. Run the query n_queens(8, Qs), labeling([ff], Qs).
OBSERVED:
This now complains about a sandbox restriction.

No permission to call sandboxed `source_location(_3028,_3030)'
Reachable from:
	  system:'$assert_load_context_module'(A,B,C)
	  system:'$load_file'(A,B,C)
	  system:'$load_files'(A,B,C)
	  load_files(A,B)

Syntax error: Operator expected

Syntax error: Operator expected

procedure `n_queens(A,B)' does not exist

EXPECTED:
Solution to n-queens

This bug impacts https://swish.swi-prolog.org/p/pwp_trainconsists.swinb

**Comment by JanWielemaker** [comment]
Fixed in latest SWI-Prolog (GIT) and public swish site.
