### ISSUE TITLE
Feature request SWISH “first row = header” option.

### ISSUE THREAD

**Issue by jburse** [SWI-Prolog/swish#130]
I suggest a “first row = header” boolean option, as 
for example also found in microsoft office table styles.

This would allow for rapid prototyping of tables
with dynamic columns and their headers, like here:

<img width="547" alt="Bildschirmfoto 2020-09-18 um 11 13 13" src="https://user-images.githubusercontent.com/5411487/93580406-090aae80-f9a0-11ea-875b-059fff897a3e.png">

Source code:

**Valuation of propositional formula.**
With dynamic table.
https://swish.swi-prolog.org/p/Valuation2.swinb

**Comment by JanWielemaker** [comment]
2bb40f9a338c95dfdc32cfb45748e7aad5e19754 allows for `header(first_row)`.
