### ISSUE TITLE
Table renderer doesn't use priority 1200 for cells

### ISSUE THREAD

**Issue by jburse** [SWI-Prolog/swish#132]
Was using the SWISH table renderer in a little Prolog notebook:

```
M = 2,
T =
Nr        Rule        Formula
1        'ax-2'        ((p->f->q)->(p->f)->p->q)
2        'ax-1'        ((f->q)->p->f->q)
3        'ax-ef'        (f->q)
4        'ax-mp'(2, 3)        (p->f->q)
5        'ax-mp'(1, 4)        ((p->f)->p->q) 
```
The Prolog notebook is here:

**Find a Hilbert proof in varity of propositional logics**
https://swish.swi-prolog.org/p/Hilbert3.swinb

I think there is a glitch in the table renderer. The table cells 
are not written with priority 1200. Because for example I see 
`(f->p)`. But a rendering as `f->p` should be enough as well.

**Comment by JanWielemaker** [comment]
Fixed with f10f3b0344bd3053029e2fc688adc74ae383a6f8
