### ISSUE TITLE
SWI-Prolog online search bar lets every user see all projects ever saved on the website

### ISSUE THREAD

**Issue by Nik4053** [SWI-Prolog/swish#134]
If a user removes everything in the search bar on the 'new tab' screen on https://swish.swi-prolog.org/ he will get 90000 results listing every document ever created on the site. I don't think this is the intended behaviour of the search bar.

**Comment by JanWielemaker** [comment]
This is by intend.   Unless you uncheck the _public_ tickbox while saving, your programs can be found by anyone.   The original intend with SWISH was to be a jsfiddle type of service where people can share nice coding ideas and discuss this.   In practice it has become mostly a student platform.   Still, the answer to just about any exercise can be found easily on the web and one place more won't make the difference.

**Comment by Nik4053** [comment]
Okay. Then I will close this issue.
