### ISSUE TITLE
Printing out newlines.

### ISSUE THREAD

**Issue by modulovalue** [SWI-Prolog/swish#139]
Hello everybody,

I'm using a swish query to try to print some text containing a newline.

```
X = 'hello\nworld', format(X).
``` 
fails with
```Sandbox restriction!
Could not derive which predicate may be called from
	  format(A)
```
Screenshot:
<img width="359" alt="Bildschirmfoto 2021-01-20 um 17 33 54" src="https://user-images.githubusercontent.com/24444584/105205558-ae4bb400-5b45-11eb-90c2-e69ec2509943.png">

The only way that I've found to print something that contains a new line is
```X = 'hello\nworld', format('~w', [X]).```

Is this expected behavior or a bug?

Thanks!

**Comment by JanWielemaker** [comment]
> Is this expected behavior or a bug?

This is expected.  The sandbox must be able to figure out the format specifier as this can use `~@` to call arbitrary goals.   `format('hello\nworld')` works fine, as does your solution.

A newline in e.g. `write('hello\nworld').` would be nice, but is rather hard as the argument to write is a term that is rendered as a nested HTML ``<span>`` element to allow collapsing, etc.  format/2 emits unstructured text, so we do not have that issue and can use a ``<pre>`` element.

**Comment by modulovalue** [comment]
Thank you!
