### ISSUE TITLE
No permission to call sandboxed `date_time_stamp(_G381,_G382)'

### ISSUE THREAD

**Issue by starsky51** [SWI-Prolog/swish#14]
I'm new to Prolog and am using swish to test the waters. I've been trying to add some date values into my knowledge base using the parse_time/3 function, but when I use it I receive the error:
"No permission to call sandboxed `date_time_stamp(_G381,_G382)'"

eg.
parse_time('%d/%m/%Y', '22/02/2002', X).

**Comment by JanWielemaker** [comment]
The sandboxing limitation is fixed.  The above does not work.  First of all, you've swapped the first two arguments, and second, only a rather limited set of date formats is supported.  See docs.  
See also http://swish.swi-prolog.org/p/lArIVQsO.pl
