### ISSUE TITLE
predicate_property/2 yields a sandbox error

### ISSUE THREAD

**Issue by JeanChristopheRohner** [SWI-Prolog/swish#143]
Hi!

I suspect that this is for security reasons, but would it be possible to get a query like this working 
`?-predicate_property(member(_, _), P).`?

Now it yields the error:
```
No permission to call sandboxed `'$current_module'(_1506,_1508)'
Reachable from:
	  '$syspreds':current_module(A)
	  '$syspreds':property_predicate(A,B)
	  predicate_property(A,B)
```

Kind regards, JCR

**Comment by JanWielemaker** [comment]
Oops, was missed, I guess.   Now works, but only for a given predicate that may not be module qualified for security reasons.
