### ISSUE TITLE
How to recompile CSS (working on dark theme for SWISH)

### ISSUE THREAD

**Issue by DalekDave** [SWI-Prolog/swish#145]
Hello, sorry, it's not an "issue" as such, but I have Swish running at https://prolog.collaboration.cafe and I want to dark-theme it. 

Swish is installed on an Ubuntu 20.04 server, from Git, as per the documented instructions.

The code is therefore in /var/www/swish

I have started editing values in /var/www/swish/web/node_modules/bootstrap/less/variables.less

Please could you give me (plus world) a brief explation and/or tips on how to recompile the instance's CSS to see my changes show up?

Thank you if so, and thank you for your work on Swish. :-)

**Comment by JanWielemaker** [comment]
Normally, `make min` builds the minimized JS and CSS files.  That should also update them.  `make clean` removes them and is best for local development.  Just a browser reload does give you the updated version.
