### ISSUE TITLE
Instantiation error is not correctly parsed by SWISH

### ISSUE THREAD

**Issue by WoutervdBrink** [SWI-Prolog/swish#146]
Program (in Dutch, it tests whether `Getal` is between `Getal1` and `Getal2`):
```prolog
tussen(Getal1, Getal, Getal2) :- Getal1 < Getal, Getal < Getal2.
```

Query:
```
?- tussen(2, X, 4).
```

This query fails with an instantiation error, but SWISH does not seem to 'parse' the error like it does with other errors:
```
{
  "code":500,
  "message":"Unknown error term: assertion_error(fail,pengines:event_term_to_json_data(error('6109c94a-7463-4362-955d-571ecd6c0a6a',error(instantiation_error,context(prolog_stack([frame(2,call(system:(<)/2),2<_718),frame(1,pred_line(\"tussen/3\",'pengine://6109c94a-7463-4362-955d-571ecd6c0a6a/src':0),tussen(2,_756,4))]),_678))),_658,'json-html'))"
}
```

When running this program and query locally:
```
?- tussen(2, X, 4).
ERROR: Arguments are not sufficiently instantiated
ERROR: In:
ERROR:    [9] 2<_3010
ERROR:    [8] tussen(2,_3036,4) at (...)/tussen.pl:1
ERROR:    [7] <user>
```

Let me know if more information is needed.

**Comment by JanWielemaker** [comment]
Thanks.  Fixed.   Regression is the result of using color and clickable positions in a normal terminal.    https://swish.swi-prolog.org is updated.

**Comment by WoutervdBrink** [comment]
Awesome, thanks for the quick response! [Fundament](https://www.instruct.nl/methoden/fundament-informatica/) thanks you :smile:

**Comment by JanWielemaker** [comment]
Nice to hear it is used by Fundament in secondary schools :smile:
