### ISSUE TITLE
HTML term rendering - ... option when copied then pasted adds ... into term.

### ISSUE THREAD

**Issue by EricGT** [SWI-Prolog/swish#148]
When converting the format via the ellipsis (...) and then doing a copy and paste, the copied version shows an ellipsis (...). 

Using

https://swish.swi-prolog.org/p/term%20html%20tests.swinb

![image](https://user-images.githubusercontent.com/2372050/161744352-65e68bf6-5a85-4357-b0a5-3e783934b88a.png)

![image](https://user-images.githubusercontent.com/2372050/161744380-35f19ce9-92bf-4bbc-b12e-9f1555ba83be.png)

![image](https://user-images.githubusercontent.com/2372050/161744400-1820544a-c1b7-4d99-93fd-6b13ae8032e2.png)

On Windows using Ctrl-v to paste in notepad, this is the result.

```
term(...)a)
```

---

Originally noted as an SWI-Prolog Discourse [reply](https://swi-prolog.discourse.group/t/html-term-rendering/5179/19)

**Comment by JanWielemaker** [comment]
This issue has been mentioned on **SWI-Prolog**. There might be relevant details there:

https://swi-prolog.discourse.group/t/html-term-rendering/5179/19

**Comment by JanWielemaker** [comment]
Thanks.  Was rather simple.  a98180ee289c6ab198ea2bcd38d6432dccf9628e

**Comment by EricGT** [comment]
Checked updated.
Working as expected.
