### ISSUE TITLE
Is there any way to get a trace call in the webapp?

### ISSUE THREAD

**Issue by McOmghall** [SWI-Prolog/swish#15]
I'd like to get the function trace call for each prolog statement to be able to get more information on how a statement is run.

**Comment by JanWielemaker** [comment]
Not yet.  It is on the TODO list, but that list is long :-(  In the meanwhile:

  - Test individual small predicates first
  - Use writeln(Term) to see things happen.  Make sure not to use too many as it will flood the network and your browser.

**Comment by McOmghall** [comment]
Very quick answer, thanks!
