### ISSUE TITLE
Error using `string` quasiquotation in swish

### ISSUE THREAD

**Issue by jds-amplify** [SWI-Prolog/swish#164]
Mac OS 13.2.1, swipl 9.2.2, latest swish from github:

<img width="829" alt="image" src="https://github.com/SWI-Prolog/swish/assets/6351656/b6954382-21e1-4520-a0a5-5a0863875817">

I'm not sure I understand the error.  I thought maybe it's related to sandboxing, but I get the same error even when running swish unrestricted.

Thanks.

**Comment by JanWielemaker** [comment]
You try to load the library that turns this into valid syntax as part of the same term in which it is used.    That won't work.   You should execute the use_module in a directive in the program or a notebook.
