### ISSUE TITLE
404 error dialog on first beginning a web session

### ISSUE THREAD

**Issue by jds-amplify** [SWI-Prolog/swish#165]
Local install on Ubuntu 20.04, swipl 9.2.2, latest swish from git. 

First starting a browser session at localhost:3050, I get an error dialog saying:

`{ "code":404, "location":"/undefined", "message":"Path not found: /undefined" }`

Thanks.

**Comment by JanWielemaker** [comment]
Thanks.   Fixed with 08ea8d0956b52a4583d151c9e8cf0f3578748758

**Comment by free-variation** [comment]
I now get 
```{ "code":500, "message":"http_session:http_session/3: Unknown procedure: http_session:schedule_gc/2" }```
On startup.

**Comment by JanWielemaker** [comment]
That is a Prolog library bug that got into the release.   Either get the GIT version of the development series or wait for the next release.
