### ISSUE TITLE
SWISH returns "500 Internal Server Error"

### ISSUE THREAD

**Issue by sailor-ITlab** [SWI-Prolog/swish#167]
https://swish.swi-prolog.org/
returns "500 Internal Server Error"
The Page content is
"""
Internal server error
broadcast:broadcast/1: Unknown procedure: 'effb9c31-4470-4015-a378-56dea801bd7e':http/1

[SWI-Prolog](http://www.swi-prolog.org/) httpd at ad673ba22229
"""

**Comment by JanWielemaker** [comment]
seems one of the backends failed.  Should be ok again.
