### ISSUE TITLE
Feature request: term_singletons/2 for end-users?

### ISSUE THREAD

**Issue by Jean-Luc-Picard-2021** [SWI-Prolog/swish#168]
Hi,

It seems that the SWI-Prolog built-in  term_singletons/2 is blocked:
```
No permission to call sandboxed `term_singletons(_1926,_1928)'
Reachable from:
	  show(A,B)
	  prove(A)
	  test
```
Would it be possible to de-block it?

Bye

**Comment by JanWielemaker** [comment]
Agree.  Added to latest SWI-Prolog source.     Should be there with the next release.
