### ISSUE TITLE
Feature request: easy text coloring?

### ISSUE THREAD

**Issue by Jean-Luc-Picard-2021** [SWI-Prolog/swish#169]
Hi,

What would be also swell, if we could have easy
text coloring. How can I do the following:
```
prove(F) :-
   prove(F,P), !,
   tag('<span style="color: red">'), show(P, 0'x), tag('</span>'),
   write(':'),
   tag('<span style="color: blue">'), write(F), tag('</span>'), nl.
```
Here is an example output, I have to provide a screenshot,
to show colors:

![xc](https://github.com/SWI-Prolog/swish/assets/95891213/089660bc-0056-4c6a-be02-35cc441165f8)

Does the server provide some sort of
tag/1 predicate to control the output by injecting the span HTML
element, which we can then use to submit a

CSS-style attribute from the [SWISH](https://swish.swi-prolog.org/) server to the SWISH client?

Bye

**Comment by JanWielemaker** [comment]
See https://swish.swi-prolog.org/example/html_output.swinb for dealing with HTML in SWISH.
