### ISSUE TITLE
Cannot save when server running on windows

### ISSUE THREAD

**Issue by Anniepoo** [SWI-Prolog/swish#17]
1. install SWISH by cloning on Windows 7 64 bit
2. install the javascript stuff via the 'download zip' method
3. start server
4. Browse to http://localhost:3050/
5. Enter 
main :- writeln(test).
in the editor.
6. Save the file, entering valid values in the save dialog
EXPECTED: file would save successfully
OBSERVED: 
Internal server error
read/2: I/O error in read on stream <stream>(0000000006D37090) (Permission denied)

SWI-Prolog httpd at Annie-PC

8cD something's busted

**Comment by JanWielemaker** [comment]
Thanks.  Fixed with 60132349bd783b815cd5beba5671f8ae8cb6501d
