### ISSUE TITLE
SWISH server stops ($raw_read/2)

### ISSUE THREAD

**Issue by mslazynski** [SWI-Prolog/swish#20]
Hi - I'm using the SWISH to teach students about the Prolog basics and it work very well 2 months. I'm running the swish on the Debian and use bower from the compressed archive you provide.. However lately server is getting killed nearly every day.

The only info I have is that ERROR: "'$raw_read'/2: I/O error in read on stream user_input (Input/output error)" is the last message before halt. Do you have any idea, what happens? Maybe can you tell me, how can I debug the server?

Best regards,
Mateusz Ślażyński

**Comment by JanWielemaker** [comment]
Hi -- First of all, http://swish.swi-prolog.org runs the server under Ubuntu upstart, such that it restarts if it crashes.  It also runs a separate service that checks whether the SWISH server still responds and kills it if not.  That results in approximately 2 restarts a week :(

To diagnose, you can load lib/logging.pl, which will cause it to write a detailed log.  Then there is `lib/replay.pl` (recent versions of SWISH) that can replay the Pengine interaction recorded in the log file.  Attached is the daemon script I use to start the server (named .txt to make github happy).  Please give it a try.

[swish-daemon.txt](https://github.com/SWI-Prolog/swish/files/49676/swish-daemon.txt)

**Comment by mslazynski** [comment]
Thanks for the fast reply! 
I'll study your solution in a free while.

**Comment by JanWielemaker** [comment]
Is this still open?  I've never seen this crash on the public server.

**Comment by mslazynski** [comment]
It seems to be working fine now. Thanks.
