### ISSUE TITLE
SWISH Markup -> Images

### ISSUE THREAD

**Issue by mslazynski** [SWI-Prolog/swish#21]
First, thank you for the great work, this is the best tool to teach Prolog.

But I have a little problem: I would like to include an inline image into to Notebook. Is it possible? According to http://student.phils.uj.edu.pl:3050/pldoc/man?section=pldoc-images it should be, however I tried all the presented possibilities and none of them worked? Am I missing something?

EDITED: Instead of image I am seeing this:
<img width="179" alt="screen shot 2015-12-03 at 23 03 46" src="https://cloud.githubusercontent.com/assets/8442722/11575589/2bce6454-9a12-11e5-9655-1dc5c9d0011b.png">

**Comment by JanWielemaker** [comment]
At this moment that doesn't work.  That has mostly to do with the fact that the notebooks are not stored in proper files, which causes the search process for the image file to fail.   Should be possible to fix, although that requires some work.   I'm not making any promises.

Are you using notebooks to create your teaching material?  I would like to have a look, though I fear it is in Polish ...

**Comment by JanWielemaker** [comment]
Note that the current version supports HTML cells that let you do all this easily (at the cost of more typing)

**Comment by mslazynski** [comment]
HTML solves the problem.

Sorry, that responding took me nearly a year. Unfortunately, as you correctly assumed, it is in Polish. The second thing is that it is directed for undergraduates studying cognitive science and it is a really basic course. Doesn't include meta-programming, modules, even recursion is very basic. I'm trying to teach them rather how to use patterns like map/filter/reduce; I believe it is more useful in context of data processing.

**Comment by JanWielemaker** [comment]
Thanks for the download.  Can you comment a little on your experience, and possible most interesting the things that could be better?

**Comment by mslazynski** [comment]
Based on my experience, notebooks (jupyter, swish) are pretty nice way to present didactic materials and experiment with a programming language.
I don’t have any complains or ideas in this area.

However, I would love to see a way to automatically evaluate code written by student, e.g. by adding unit tests to „program" and „query” fields.
User would be given an exercise, e.g write a specific query and the would automatically receive a feedback: „Good job!” or „It works only for this specific program, if I have added a new fact to it, I would receive a wrong answer”, based on the tests implemented beforehand by a teacher. There are many details which would have to be discussed, but in general this kind of testing would greatly improve my workflow 

—
Mateusz Ślażyński

**Comment by JanWielemaker** [comment]
Interesting thought.   You can get somewhere using some creativity with what is there.  For example by providing a test file that can be included by the student.  As in

```{prolog}
:- include(test_assignment_1).

<student's code>
```

After which the student can run some defined query to check his solution against the tests.

A bit more principled approach would be nice though :)

**Comment by mslazynski** [comment]
It makes sense - I use similar approach already in Jupiter notebooks.

BTW Two unrelated questions:
1) what virtual machine is currently used by swi-prolog? Is it ZIP machine or a modified WAM?
    I’m asking because I was teaching a bit about virtual machines and I’m curious.
2) why did you implemented swish as a separate service instead of investing time to create another kernel for Jupyter?
—
Mateusz Ślażyński

**Comment by JanWielemaker** [comment]
> 1) what virtual machine is currently used by swi-prolog? Is it ZIP machine or a modified WAM? I’m asking because I was teaching a bit about virtual machines and I’m curious.

It is ZIP inspired.  Notably it passes arguments over the stacks (it has no registers).

> 2) why did you implemented swish as a separate service instead of investing time to create another kernel for Jupyter?

When we (me and Tobjorn) started, there was only iPython notebooks.  There was some idea of adding other languages to it, but all that was still pretty immature.

The second reason is that Prolog is a rather different language.  In my experience this typically makes a poor fit.  You already see this, where Jupyter is basically a single-user solution (I see there is JupyterHub, but that mostly manages multiple single user notebooks if I read the page correctly), SWISH started being a shared resource.  That is possible due to the fact that most Prolog code is side-effect free.   The main application for SWISH is _DataLab_, aiming at shared exploration of a dataset.  That works great in Prolog, but far less so in an imperative language.
