### ISSUE TITLE
Feature request: Prolog variables in labels

### ISSUE THREAD

**Issue by triska** [SWI-Prolog/swish#25]
To elegantly solve  [**roadmap item 22**](https://github.com/SWI-Prolog/roadmap/issues/22), I need a way to show the actual Prolog variables in Graphviz **labels**. Note that the same variable can occur at different positions in the BDD. An example of a BDD as I would like to show it is:

![BDD](http://metalevel.at/card.svg)

The dot specification for this is:

    digraph G {
            4 [label="X";fontname="Palatino-Roman"];
            2 [label="Y";fontname="Palatino-Roman"];
            0 [label="Z";fontname="Palatino-Roman"];
            3 [label="Y";fontname="Palatino-Roman"];
            1 [label="Z";fontname="Palatino-Roman"];
            false [fontname="Palatino-Bold"];
            true [fontname="Palatino-Bold"];

            edge [style="dotted"];
            4 -> 2;
            2 -> false;
            0 -> false;
            3 -> 0;
            1 -> true;

            edge [style="filled"];

            4 -> 3;
            2 -> 0;
            0 -> true;
            3 -> 1;
            1 -> false;

            }

Note that variables are correctly shown in the Graphviz output if they appear directly as *nodes*. However, I need them to appear in the *labels*.

Could you please provide a way to make the actual variable names available to the graphviz renderer? Specifically, I actually need them for showing the **residual goals** of a query. Maybe this helps to simplify the task:

Would it work to provide a renderer like `residuals`, and pass to it an atomic representation of the query variables in addition to the bindings? This renderer could then generate a `dot/1` term, and this could be shown using the graphviz renderer.

Note that this would also be beneficial for other uses cases, such as drawing the actual graph representation of plain Prolog terms. Currently, the variables are of course distorted, also in the `graphviz` notebook example.

**Comment by JanWielemaker** [comment]
I had a brief look.  As it is, the usual toplevel stuff happens (break cycles, extract residuals), then
all variables with known names are bound to '$VAR'(Name) (where Name is an atom),
Variables with equal value are identified and finally

  - for each value bound to a variable, the renderer is called.  
  - for each residual goal, the renderer is called with `Vars` bound to `[]`.  Thus, if the vars-list
    is `[]`, you are handed a residual goal, else a normal variable binding.

You can use nodes of the form `Var1 -> Var2` because in the end the value is handed to
print/1, which renders '$VAR'('Var1') as Var1.  You can use labels in the intermediate graphviz
representation as long as you use `format(string(S), '~p', [Val])` to generate the label string.

So, I think the variable names are not really the problem.  Probably it is a real problem that
the rendering hook gets the residuals one-by-one, while I fear you want all of them together,
right?

**Comment by triska** [comment]
Yes, ideally, I would like to reason about all residual constraints together.

However, in this special case (it will make *less* sense in other cases), I am willing to adjust `library(clpb)` to accommodate the renderer so that at least the CLP(B) residuals that form the BDD are all summarized in a single term.

Suppose I adjust CLP(B) to give us:

    ?- set_prolog_flag(clpb_residuals, bdd).
    true.

    ?- sat(card([2],[X,Y,Z])).
    '$clpb_bdd'([node(4)- (v(X, 0)->node(3);node(2)),
       node(2)- (v(Y, 1)->node(0);false),
       node(0)- (v(Z, 2)->true;false),
       node(3)- (v(Y, 1)->node(1);node(0)),
       node(1)- (v(Z, 2)->false;true)]).

Now the terms that represent the BDD occur as a **single term** `$clpb_bdd/1`.

Could you please provide the infrastructure so that I can hook a renderer into such residual goals, or better yet, let it handle the residual goals in their entirety?

**Comment by triska** [comment]
Regarding the variable names, please see the very last example in the [SWISH notebook](http://swish.swi-prolog.org/example/render_graphviz.swinb) about graphviz rendering: The variable `X` in the query

    ?- A = f(1, a, `XY`, "XY", X), gvtree(A, T).

appears not as `X`, but as `_G3904` in the picture! This is unfortunate, because this really isn't the same term, only a variant is shown.

**Comment by JanWielemaker** [comment]
I figured this out.  Please try the above notebook again :)  See the comment just above the notebook for why this works.  Note that this problem arises if you process a term in the Pengine to a term for the graphviz renderer because the first runs on the pure Prolog term while the second runs on the term after the toplevel did its magic.  The problem does not arise if you write a dedicated new rendering library for SWISH.

I think you need to write a bdd renderer where you translate the term into a term suitable
for the graphviz renderer and then call the graphviz' renderer translation.   I'm happy to include
such a renderer.

**Comment by triska** [comment]
Awesome work, thank you Jan! I have now pushed a change to `library(clpb)` that emits a `dot/1` term when the flag `clpb_residuals` is set to graphviz. Hence, a BDD can now already be drawn in SWISH if you use the following **two** directives:

    :- set_prolog_flag(clpb_residuals, graphviz).
    :- use_rendering(graphviz).

I think this coupling could be improved. Is there a way to detect, from within `library(clpb)`, whether the graphviz renderer is currently enabled?

I noticed two further issues:

- The flag `toplevel_print_options` does not affect the residual goals, but it **should**:

<pre>
?- [library(clpb)].
true.

?- set_prolog_flag(clpb_residuals, graphviz).
true.

?- sat(card([2],[X,Y,Z])).
sat(X*Y#X*Y*Z#X*Z#Y*Z),
dot(digraph([node(4, [label=X]), node(2, [label=Y]), node(0, [label=Z]), node(3, [label=Y]), node(1, [... = ...]), edge([...]),  (... -> ...)|...])).

?- <b>set_prolog_flag(toplevel_print_options, [quoted(true), portray(true)]).</b>
true.

?- sat(card([2],[X,Y,Z])).
sat(X*Y#X*Y*Z#X*Z#Y*Z),
<b>dot(digraph([node(4, [label=X]), node(2, [label=Y]), node(0, [label=Z]), node(3, [label=Y]), node(1, [... = ...]), edge([...]),  (... -> ...)|...])).</b>
</pre>

- I cannot use the `fontname` property for graphviz labels. Please try it by commenting out line 1611 in `library(clpb)`.

**Comment by JanWielemaker** [comment]
Seems to work!  I wonder whether it isn't a better idea to add a bdd renderer to SWISH though.  Do you really want code in library(clpb) that depends on the SWISH rendering framework to do its
job?  For the points:

  - toplevel_print_options is not settable and if it would will indeed not help as the printing happens
    in a different thread as the pengine.  Possibly one can hack around, but the idea is that the
    HTML rendering is much more flexible anyway.
  - Added a declaration to make fontname work.  In contrast to the docs, some values may not
    be quoted for graphviz (at least that is my experience).  This blocks a purely value-based
    approach to represent every possible value.

Time for some nice notebooks to explain a little more about clp(b)?

**Comment by triska** [comment]
I have filed a [issue #139](https://github.com/SWI-Prolog/swipl-devel/issues/139) about `toplevel_print_options`, completely independent from pengines and SWISH.

I share the same question about where to best put the renderer, and here is more information about it: I want to make it easy for users to enable showing BDDs. Suppose I have a small renderer, say `bdd`, and users can simply enable it with the **single** directive:

    :- use_rendering(bdd).

It is clear how this could work: This renderer simply "listens" for the `sat/1` residual goals, (re-)creates a BDD from the `sat/1` goal, then creates a `dot/1` term from the BDD, and then hands it to the `graphviz` renderer.

The problem with this approach is that the formula can blow up exponentially when `library(bdd)` creates the `sat/1` residual, even though the BDD itself is quite small and would be suitable for rendering!

Therefore, the renderer needs to have a way to access the BDD representation directly, but that (BDD) representation is normally not emitted by `library(clpb)`. It is only emitted when setting `clpb_residuals` to `bdd`. However, I would like to have a way that does not require users to set **both** directives (`clpb_residuals` and `use_rendering`). Instead, I would like to have only one directive that does both: Cause `library(clpb)` to omit the BDD representation, and enable the graphviz renderer of the BDD.

Therefore my question: Is there a way to let `library(clpb)` know which rendering is currently in effect? Alternatively, maybe setting the `bdd` renderer should automatically imply `clpb_residuals` = `bdd`. One way or the other, the library and the renderer must cooperate in this case due to the vast cost that can be involved when going from the BDD representation to the normal residual goals.

Once all this is implemented, it is indeed time for a notebook about CLP(B) ;-)

**Comment by JanWielemaker** [comment]
A single use_rendering(bdb) to affect clpb is of course what we are after.   clpb doesn't know from what module context it is being used unless you want to turn the interface into meta predicates.  That
seems absurd to me.    One way I see is that use_renderer can have side effects by adding
a hook to the rendering module or something similar.  Smells a bit dubious too, so I'll sleep on it
for at least a night ...    Will be mostly in meetings this week, so don't expect immediate answers.

Possibly we can add a term-expansion rule to expand `:- use_rendering(bdb)` into itself followed
by a set_prolog_flag?   That rule could be part of swish.pl that contains code to preload libraries and make them work with SWISH anyway.

**Comment by triska** [comment]
It is definitely very good to think things over for a few days. I like your idea about term expansion a lot! I will prepare something in this direction and submit a pull request to see how this may work.

**Comment by triska** [comment]
Some more food for thought:

Suppose we first concentrate on the default CLP(B) representation for residual goals, i.e., `sat/1` goals in algebraic normal form, as in:

<pre>
?- sat(X+Y).
<b>sat(X=\=X*Y#Y)</b>
</pre>

This is obviously the "nice" representation that users are used to. Main advantage: Its argument is an actual CLP(B) expression and it can be directly pasted back on the toplevel to obtain the same program. Drawback: It can take some time to compute this representation. But still, overall, this is the preferred representation in many ways for users, and if this could be used to show BDDs via graphviz (and then let users toggle between `sat/1` goals and BDDs), then a great number of use cases would be successfully solved without even needing to set `clpb_residuals` to `bdd`. Of course, the renderer could also be made to handle the case when `clpb_residuals` is set to `bdd`. In fact, this is the case that already works.

So, we need a way to obtain the BDD corresponding to each `sat/1` residual goal. At first, this seems easy enough, because we can of course simply ask `library(clpb)` itself for the BDD of a CLP(B) expression, using for example the following steps:

1. post the `sat/1` constraint exactly as it appears in the residual goals
2. store the current value of `clpb_residuals`, and then set it to `bdd`
3. use `copy_term/3` to obtain the nodes of the BDD
4. set `clpb_residual` to its previous value (obtained in (2))
5. render the nodes using graphviz.

Here is Prolog code for the renderer that is supposed to work **both** with `clpb_residuals` set to `bdd` **and** with the default representation of CLP(B) residual goals:

<pre>
term_rendering(Goal, Vars, Options) -->
        { debug(graphviz(vars), 'Goals: ~q', [Goal]) },
        (   { Goal = '$clpb_bdd'(Ns),
              is_list(Ns) } -> []
        ;   { Goal = sat(Sat) } ->
            (   { current_prolog_flag(clpb_residuals, OldFlag) } -> []
            ;   { OldFlag = default }
            ),
            { term_variables(Sat, Vs),
             % convert sat/1 goal to BDD nodes, using copy_term/3
              setup_call_cleanup(set_prolog_flag(clpb_residuals, bdd),
                                 catch((sat(Sat),
                                        copy_term(Vs, Vs, [clpb:'$clpb_bdd'(Ns)]),
                                        % reset all attributes
                                        throw(nodes(Vs,Ns))),
                                       % Vs recreate the bindings in nodes Ns
                                       nodes(Vs,Ns),
                                       true),
                                 set_prolog_flag(clpb_residuals, OldFlag)) }
        ),
        { nodes_dot_digraph(Ns, Dot) },
        swish_render_graphviz:term_rendering(Dot, Vars, Options).
</pre>

Unfortunately, this does not work! The reason is that the renderer is not handed the actual `sat/1` residual  goals (including variables), but a term where the variables already appear as ground terms.

For this reason, it is hard or currently even impossible to even draw the most elementary residual goals of `library(clpb)` using a SWISH renderer.

I think the initial feature request therefore still stands: I somehow need access to **both** the variable **and** its textual representation to draw the BDD. I need the variable because I need to convert the `sat/1` goal to a BDD. And I need the textual representation because I need to use this as the label for `graphviz`. Is there any chance you could generalize the rendering infrastructure to provide us with both things?

Maybe it could work to store the textual representation as an **attribute** of each variable to let renderers know both aspects?

**Comment by JanWielemaker** [comment]
Hmm.  I like the overall approach.  It fails, but I think a version of varnumbers/2 that returns the
variable names could help, no?

**Comment by triska** [comment]
Yes, that would definitely help. I would prefer to have the names as part of the interface to renderers though, and not need to call such a predicate in the renderer itself.

Would it work to pass the actual Prolog terms to renderers, and in addition let them have a way to know the textual representation of each variable? An interface similar to that of `read_variables/2` could be used, i.e., pass along a list of `Name=Var` pairs.

I have now collected some experience with renderers that must work on variabes (both in residual goals and other bindings), and I find working on the current representation extremely error prone and also hard to debug: For example, in debug output, it often seems that a variable occurs even when it is in fact a ground term of the form&nbsp;`'$VAR'(X)`. In such cases, I would rather work on the actual variables, and have their names available separately.

**Comment by JanWielemaker** [comment]
I'm not so sure.    The overall idea behind the renderers was to render a Prolog term that represents the binding of a variable graphically using HTML5/JavaScript.  I.e., the bottom line is that you hand
the term to print/1 as it always worked in Prolog.  The HTML alternative is term//1, which adds some
highlighting and (yet incomplete) folding and unfolding.  The additional renderers basically recognise the shape, use that to create some sort of container (table, tree, graph, ...) and render the Prolog terms in the cells/nodes/...  At this level you are preferably no longer interested in the oddities of the toplevel such as variables sharing the value, cycles, residuals, attributes, etc.

The current infrastructure seems mostly adequate for that.  You want to render residual goals using a different shape (not just syntax) than the one you normally present to the user.   If we can accommodate that, I'm mostly happy, also if it isn't the most beautiful solution.

So far, creating the term with variables and bindings using the code (current git) below and following your route going back to clp(b) to translate the residual goals into a BDD may do the trick.

```{prolog}
        ...,
	varnumbers_names(Term, Copy, Bindings0),
	include(named_binding, Bindings0, Bindings).

named_binding(Name=_) :-
	atom(Name).
```

An alternative might be to have a sat_bdd(Expression, BDD) with produces a bdd term in clpb and have the renderer deal with that?  To me, this makes some sense as well.

**Comment by triska** [comment]
I have found a way to handle all issues uniformly, at least for now:

- everything works exactly as on the normal toplevel, `sat/1` residual goals are the default
- users can use the `bdd` renderer just like any other renderer
- the `bdd` renderer knows how to handle `sat/1` **and** `clpb:'$clpb_bdd'/1` residuals
- alas, setting `clpb_residuals` to `bdd` in SWISH does not change the residual goals from the toplevel.
- **but**, and that's the good news, setting `clpb_residuals` **does** affect `copy_term/3`
- therefore, as a workaround, if the projection to `sat/1` is too slow, users can use a combination of `copy_term/3` and `del_attrs/1` to obtain *only* the BDD representation. This basically gives you `sat_bdd/2` *without* needing any new interface predicates in `library(clpb)`. Note also, since renderers are not applied recursively to terms, we also need to single out the residual goal

For example:

<pre>
?- length(Vs, 20), sat(card([2],Vs)), 
   <b>copy_term(Vs, Vs, Gs), maplist(del_attrs, Vs), Gs = [BDD]</b>.
</pre>
In this case, a nice BDD is soon visible if you include `:- set_prolog_flag(clpb_residuals, bdd).` in the snippet, but the projection to `sat/1` goals is costly.

Mostly due to the need for `del_attrs/1`, this is still a bit of a kludge, and I hope the eventual solution is more elegant. When extending and revising the interface for renderers, please take into account the issues raised in #27.

For now, I think pull request #26 is ready for merging! I hope rendering BDDs so easily attracts a few students and researchers who need this.

Thank you for the new interface predicates you created to enable such drawings!

**Comment by JanWielemaker** [comment]
I think this is complete now
