### ISSUE TITLE
Table rendering examples broken

### ISSUE THREAD

**Issue by torbjornlager** [SWI-Prolog/swish#29]
The two last examples in the note book at 

[http://swish.swi-prolog.org/example/render_table.swinb](http://swish.swi-prolog.org/example/render_table.swinb)

seem to be broken.

**Comment by JanWielemaker** [comment]
Hi!   I don't know what is wrong with the last.  The one-but-last was definitely wrong.  Fixed.

P.s.  Your original pengines idea is getting back into swish by introducing HTML cells in notebooks.  Hope to make this public in a week or so.

**Comment by torbjornlager** [comment]
Hmm, I'm sure I got just a list of row/2 terms when I tried. Well, it seems to work now!

HTML cells in notebooks - that will be awesome!
