### ISSUE TITLE
Insert cells in notebook in full screen mode

### ISSUE THREAD

**Issue by borisvassilev** [SWI-Prolog/swish#33]
Hello,

this is definitely just a minor nuisance and nothing more.

When a notebook is in "full screen" mode, and gets too long (vertically), there is no way to insert cells at the bottom of the notebook. Folding all cells helps only for another few cells.

Would it be at all useful to keep the notebook actions ("Delete", "Copy", ... "Insert cell below") docked somewhere even in full screen mode?

**Comment by JanWielemaker** [comment]
Pushed a patch to keep the hamburger in the top-level corner.   I think we can invent a better UI for editing the notebook, but fixing the position was easy.
