### ISSUE TITLE
Warnings like: "Wrong context: register_renderer"

### ISSUE THREAD

**Issue by olsky** [SWI-Prolog/swish#34]
I'm getting these messages, what am I doing wrong?

> Warning: /home/olsky/swi-prolog/lib/swipl-7.3.19/swish/swish.pl:172:
>         Using CLP(FD) with bounded arithmetic may yield wrong results.
> Warning: /home/olsky/swi-prolog/lib/swipl-7.3.19/swish/swish.pl:173:
>         Using CLP(B) with bounded arithmetic may yield wrong results.
> ERROR: /home/olsky/swi-prolog/lib/swipl-7.3.19/swish/lib/render/table.pl:42:
>         Wrong context: register_renderer/2 can only be used in a directive
> Warning: /home/olsky/swi-prolog/lib/swipl-7.3.19/swish/lib/render/table.pl:42:
>         Goal (directive) failed: swish_render_table:register_renderer(table,"Render data as tables")
> ERROR: /home/olsky/swi-prolog/lib/swipl-7.3.19/swish/lib/render/codes.pl:37:
>         Wrong context: register_renderer/2 can only be used in a directive
> Warning: /home/olsky/swi-prolog/lib/swipl-7.3.19/swish/lib/render/codes.pl:37:
>         Goal (directive) failed: swish_render_codes:register_renderer(codes,"Render a list of character codes")
> ERROR: /home/olsky/swi-prolog/lib/swipl-7.3.19/swish/lib/render/svgtree.pl:43:
>         Wrong context: register_renderer/2 can only be used in a directive
> Warning: /home/olsky/swi-prolog/lib/swipl-7.3.19/swish/lib/render/svgtree.pl:43:
>         Goal (directive) failed: swish_svgtree:register_renderer(svgtree,"Render term as a tree")
> ERROR: /home/olsky/swi-prolog/lib/swipl-7.3.19/swish/lib/render/graphviz.pl:45:
>         Wrong context: register_renderer/2 can only be used in a directive
> Warning: /home/olsky/swi-prolog/lib/swipl-7.3.19/swish/lib/render/graphviz.pl:45:
>         Goal (directive) failed: swish_render_graphviz:register_renderer(graphviz,"Render data using graphviz")
> ERROR: /home/olsky/swi-prolog/lib/swipl-7.3.19/swish/lib/render/c3.pl:45:
>         Wrong context: register_renderer/2 can only be used in a directive
> Warning: /home/olsky/swi-prolog/lib/swipl-7.3.19/swish/lib/render/c3.pl:45:
>         Goal (directive) failed: swish_render_c3:register_renderer(c3,"Render data as tables")
> ERROR: /home/olsky/swi-prolog/lib/swipl-7.3.19/swish/lib/render/url.pl:36:
>         Wrong context: register_renderer/2 can only be used in a directive
> Warning: /home/olsky/swi-prolog/lib/swipl-7.3.19/swish/lib/render/url.pl:36:
>         Goal (directive) failed: swish_render_url:register_renderer(url,"Make URLs clickable")
> 
> 
> Init Web-Server ...
> 
> % Started server at http://localhost:8050/

**Comment by JanWielemaker** [comment]
You surely have an old version of SWI-Prolog and you probably have an incomplete version.  Try installing the latest version and run `?- check_installation.` to see whether anything is missing.  
JPL is often missing.  That is fine.  SWISH needs a lot though.

**Comment by olsky** [comment]
Thank you, Jan.

I have excluded JPL and GMP... as I do not need them. I think also not required for swish.

Is the ver 7.3.19 so old? :-(

And then here is check_installation:


1 ?- check_installation.
% Checking your SWI-Prolog kit for common issues ...
%
% Version: ............. 7.3.19
% Address bits: ........ 64
% Architecture: ........ x86_64-linux
% Installed at: ........ /home/olsky/swi-prolog/lib/swipl-7.3.19
% Cores: ............... 2
%
% Checking gmp ................................. not present
Warning: See http://www.swi-prolog.org/build/issues/gmp.html
% Checking command_line_editing ................ ok
% Loading library(archive) ..................... ok
%   Supported filters: bzip2, compress, gzip, grzip, lrzip, lzip, lzma, lzop, none, rpm, uu, xz
%   Supported formats: 7zip, ar, cab, cpio, empty, gnutar, iso9660, lha, mtree, rar, raw, tar, xar, zip
% Loading library(cgi) ......................... ok
% Loading library(crypt) ....................... ok
Warning: library(bdb) .......................... NOT FOUND
Warning: See http://www.swi-prolog.org/build/issues/bdb.html
Warning: library(double_metaphone) ............. NOT FOUND
Warning: See http://www.swi-prolog.org/build/issues/double_metaphone.html
% Loading library(filesex) ..................... ok
% Loading library(http/http_stream) ............ ok
% Loading library(http/json) ................... ok
Warning: library(isub) ......................... NOT FOUND
Warning: See http://www.swi-prolog.org/build/issues/isub.html
Warning: library(jpl) .......................... NOT FOUND
Warning: See http://www.swi-prolog.org/build/issues/jpl.html
% Loading library(memfile) ..................... ok
% Loading library(mime) ........................ ok
Warning: library(odbc) ......................... NOT FOUND
Warning: See http://www.swi-prolog.org/build/issues/odbc.html
% Loading library(pce) ......................... ok
Warning: library(pdt_console) .................. NOT FOUND
Warning: See http://www.swi-prolog.org/build/issues/pdt_console.html
Warning: library(porter_stem) .................. NOT FOUND
Warning: See http://www.swi-prolog.org/build/issues/porter_stem.html
% Loading library(process) ..................... ok
% Loading library(readutil) .................... ok
% Loading library(rlimit) ...................... ok
% Loading library(semweb/rdf_db) ............... FAILEDsource_sink `library(rdf)' does not exist
Warning: Goal (directive) failed: rdf_db:use_module(library(rdf))
Warning:
Warning: See http://www.swi-prolog.org/build/issues/semweb/rdf_db.html
% Loading library(semweb/rdf_ntriples) ......... ok
% Loading library(semweb/turtle) ............... ok
% Loading library(sgml) ........................ ok
% Loading library(sha) ......................... ok
Warning: library(snowball) ..................... NOT FOUND
Warning: See http://www.swi-prolog.org/build/issues/snowball.html
% Loading library(socket) ...................... ok
% Loading library(ssl) ......................... ok
% Loading library(syslog) ...................... ok
Warning: library(table) ........................ NOT FOUND
Warning: See http://www.swi-prolog.org/build/issues/table.html
% Loading library(time) ........................ ok
% Loading library(tipc/tipc) ................... ok
% Loading library(unicode) ..................... ok
% Loading library(uri) ......................... ok
Warning: library(uuid) ......................... NOT FOUND
Warning: See http://www.swi-prolog.org/build/issues/uuid.html
% Loading library(zlib) ........................ ok
Warning: Found 12 issues.

**Comment by JanWielemaker** [comment]
Same problem as the prolog_file_type/2 issue: installation inside the SWI-Prolog installation.  Pushed a fix for this one too.

**Comment by olsky** [comment]
Oops... see the updated info> 

`Apr 15, 2016: SWI-Prolog 7.3.20 supports SWISH completely.`

I will update it... thank you!

**Comment by JanWielemaker** [comment]
Don't trust the _SWI-Prolog X.Y.Z supports SWISH completely_ too much.  I frequently forget to update it :)   There is quite some development in this area.   I do try to keep swish usage compatible with previous versions.

**Comment by olsky** [comment]
Ok! :)

thank you!
