### ISSUE TITLE
undefined: swish_page:prolog_file_type/2

### ISSUE THREAD

**Issue by olsky** [SWI-Prolog/swish#35]
I receive the following message, when selecting any of Examples-menue options:

![image](https://cloud.githubusercontent.com/assets/6040444/16043114/6dad59ba-323e-11e6-8cf3-7757a774341a.png)

Am I missing any setup? 

I'm running swipl 7.3.19, and got swish from github 2-3weeks ago.

Thank you

**Comment by olsky** [comment]
Ok, adding these lines to swish/swish.pl file, fixes this issue.

```
swish_page:prolog_file_type(pl, prolog).
swish_page:prolog_file_type(pro, prolog).

```

**Comment by JanWielemaker** [comment]
I see.  Seems you dumped the SWISH into the SWI-Prolog installation.  That didn't work as files loaded from their bypass the `user` module.   Pushed a fix to swish to make that work.  Your fix is only a partial one.   I would always include gmp unless there is some compelling reasons not to.  The constraint libraries use it for bitmaps that get pretty small without gmp.   There are surely several patches that affect SWISH after 7.3.19 :)
