### ISSUE TITLE
Missing software license

### ISSUE THREAD

**Issue by frnmst** [SWI-Prolog/swish#40]
Hello,
I see that some files have the GPL header while others don't. Moreover I can't see any LICENSE nor COPYING file in the root directory. Have a look at this https://www.gnu.org/licenses/license-list#NoLicense to see why a missing license is dangerous.
In order for a software to be free, license headers should be present in every source code file: https://www.gnu.org/licenses/gpl-faq.en.html#LicenseCopyOnly
https://www.gnu.org/licenses/gpl-faq.en.html#NoticeInSourceFile

**Comment by JanWielemaker** [comment]
Good point.   I think I fixed most of them now.

**Comment by Anniepoo** [comment]
8c/ Just as I was about to ask about a non GPL license for SWISH

**Comment by frnmst** [comment]
I'm sorry to answer after more than 2 months.

That's great.
Thanks.
