### ISSUE TITLE
writeln/1 produces a newline too many

### ISSUE THREAD

**Issue by SQB** [SWI-Prolog/swish#41]
Considering
```
test :-
    write('This is'),
    write(' a'),
    writeln(' test.'),
    write('As well as this.').
```
`?- test.` yields
```
This is a test.
As well as this.
true.
```
when run in SWIPl, but 
```
This is a
test.
As well as this.
true
```
when run in SWISh.

Apparently, a newline is written _before_ the term as well as after.

**Comment by JanWielemaker** [comment]
Fixed.    Format/2 is a much better alternative for writing output that includes data though.
