### ISSUE TITLE
BDD renderer is currently broken

### ISSUE THREAD

**Issue by triska** [SWI-Prolog/swish#45]
Commit c30722b5e83ecf23ee2b4c44cc97648187d6d432 has broken use cases of the **BDD&nbsp;renderer** that previously worked.

See [**broken_bdd_renderer.pl**](http://swish.swi-prolog.org/p/broken_bdd_renderer.pl) for an example:

**Program**:

<pre>
:- use_rendering(bdd).
:- use_module(library(clpb)).
:- set_prolog_flag(clpb_residuals, bdd).
</pre>

**Query**:

<pre>
?- length(Vs, 3), sat(card([2],Vs)),
   copy_term(Vs, Vs, [BDD]), maplist(del_attrs, Vs).
</pre>

This yields an **instantiation error**.

When working on this issue, please take into account the information contained in #25 and #27. Thank you!

**Comment by JanWielemaker** [comment]
Fixed with 071295b8bfc72557c8b74bdad16373de9dad6841.  #27 is unrelated and explained in the reply.
