### ISSUE TITLE
Trace doesn't follow alternative queries

### ISSUE THREAD

**Issue by kurka** [SWI-Prolog/swish#46]
When debugging a code in Swish that present multiple answers, only the first execution of the code is traceable, while the others run without a debugger.

For example:

If I have the program:
```prolog
test(a).
test(b).
test(c).
```

and then run it as:
```prolog
trace, (test(X)).
```
the swish interface presents a nice trace interface, showing all the calls for the first case (`test(a)`), but when "next" is pressed in the interface, the next results are shown without debugging.

**Comment by JanWielemaker** [comment]
Thanks.  Fixed.
