### ISSUE TITLE
Load swinb files from git into notebooks

### ISSUE THREAD

**Issue by samwalrus** [SWI-Prolog/swish#56]
I can currently load a program using :
http://swish.swi-prolog.org/?code=https://raw.githubusercontent.com/samwalrus/machine_learning/master/classifiers/distances.pl&q=data(X),test(T),data_instance_k_classification(X,T,3,C).

But  it would be great to be able load a swinb notebook file that I have made in
swish and then download and placed on github in the same way.
At the moment it loads as a program not a notebook.

**Comment by JanWielemaker** [comment]
Added with commit 604165ca3aae5bb59d8424b6e3a0e547ee4ff19c
