### ISSUE TITLE
How to run SWISH without restrictions in one terminal command, like jupyter notebooks?

### ISSUE THREAD

**Issue by robertsimione** [SWI-Prolog/swish#57]
I'm trying to do the kind of development in SWISH that I'm used to in Jupyter notebooks, but one hurdle is that I would like some way to just run the swish server and start using swish without restrictions on the libraries available, without having to commit and remember a user profile. With jupyter I just run `jupyter notebook` on the command line and start developing scripts in Jupyter's web UI. Is there, or can there be, a similar one liner I can run on the command line for SWISH to similarly just start developing without restrictions?

**Comment by JanWielemaker** [comment]
You can load `ide.pl` from the swish directory and simply run `?- swish.`  It is merely a start and hasn't been updated with the recent rewrites that modularize swish.   Still seems to start, but I don't know how far it goes.

Note that this is relatively unsafe as anyone with access to your computer can quite easily steal the connection.   This is probably also true for Jupyter as there is no proper safe way to start a browser from an application and make sure no other browsers can connect (AFAIK).

**Comment by robertsimione** [comment]
This is very helpful. Thanks Jan!
