### ISSUE TITLE
Tab Completion 

### ISSUE THREAD

**Issue by robertsimione** [SWI-Prolog/swish#58]
If I am correct in understanding that SWISH is becoming the future SWI-Prolog development environment, it would be really helpful is SWISH could have tab-completion like Jupyter notebooks have.

**Comment by JanWielemaker** [comment]
Not sure what you are after.  There is Control-space completion in the editor.  AFAIK, that is the default binding in most modern editors.  It surely is the default for CodeMirror.

And yes, turning SWISH into a full IDE is part of the plan.  As is though, it is still way behind the SWI-Prolog native IDE for program development.  It is doing quite nicely for playing with queries on some dataset though.

**Comment by robertsimione** [comment]
Thanks Jan, that helps a lot.
