### ISSUE TITLE
scroll required to see whole SVG graphics

### ISSUE THREAD

**Issue by friguzzi** [SWI-Prolog/swish#60]
SWISH now shows only part of SVG graphics, one needs to scroll to see the whole image
see 

![image](https://cloud.githubusercontent.com/assets/9638148/26418158/7d47b0c8-40bb-11e7-86c7-b79ff5aa78f1.png)

**Comment by friguzzi** [comment]
The problem seems to be due to the fact that the runner pane is not scrolled after the answer is rendered. The scroll happens only when the query is submitted and to print the abort message, no scroll is performed after the answer is shown (see runner.js)

**Comment by JanWielemaker** [comment]
I thought it was related to the SVG itself, but it seems not.  Just asking `?- length(L, 200).` show the same problem.  Not sure what you mean though.  Answers call `setState` and this does the scroll.  At least,
that is how it is intended.  If you see the real issue, please explain or send a pull-request ....

**Comment by friguzzi** [comment]
I fiddled a little bit with runner.js and I noticed that scrollToBottom is not called to render the answer. i will try to have a look but I am not very good at js

**Comment by friguzzi** [comment]
The problem is that aliveState(state) for the true state returns false, so a branch is entered in setState where scrollToBottom is not called. I will make a pull request

**Comment by JanWielemaker** [comment]
Fixed by you :) closing.
