### ISSUE TITLE
Message "The source editor has unsaved changes" when opening a new notebook with an open notebook

### ISSUE THREAD

**Issue by friguzzi** [SWI-Prolog/swish#67]
The message "The source editor has unsaved changes" appears when opening a new notebook with an open notebook. This happens for example in
http://cplint.lamping.unife.it/example/inference/inference_examples.swinb
when clicking on path_tabling.swinb.
This is due to function unload line 1052 of storage.js:
if ( data.cleanData != data.getValue() )
getValue appears to massage the notebook code: for example, it adds a newline after every `</div>`
So if the notebook was hand coded and does not contain these new lines, when we want to open a new notebook we get the message above.

**Comment by friguzzi** [comment]
I have understood the use of getValue for notebooks so I modified the code of my notebooks so that  the message "The source editor has unsaved changes" does not appear.

**Comment by JanWielemaker** [comment]
With what patch?  In general I know two reasons for this issue.  One is non-canonical white space and the other is missing cell names.  Old versions had no cell names, but they are both needed for dealing with selections in the chat inside notebooks and for plans on better handling of source locations and provenance tracking.

In both cases, saving should fix the problem.  To do so, use a local copy, login using a local account.  That should give you access right to save examples.  Now load the example, try to move away and save it.

If that doesn't solve the issue we must look closer.  If you patch is a proper solution I'd like to have it ...

**Comment by friguzzi** [comment]
I didn't patch the swish code, I patched my examples. The problem was that getValue added an empty line after `</div>`, translated `<` into `&lt;` and removed extra values from the class attribute of divs.
As I see it getValue does a form of canonization which is good for user notebooks written using swish. For example notebooks written in source form it creates the problem of the confirmation message. I think that we can stay with a clean writing of example notebooks, using the approach you mentioned to fix them.

**Comment by friguzzi** [comment]
I did as you suggested, logged in and saved the file but cell names are not added, is it normal?

**Comment by JanWielemaker** [comment]
You have to do something that triggers the cell names to be added.   This is e.g., adding a chat message, which you can't ...  Maybe simply running this from the develop console

    $(".notebook").notebook('assignCellNames')

Should be improved ...

**Comment by JanWielemaker** [comment]
> I didn't patch the swish code, I patched my examples. The problem was that getValue added an empty line after </div>, translated < into &lt; and removed extra values from the class attribute of divs.
> As I see it getValue does a form of canonization which is good for user notebooks written using swish. For example notebooks written in source form it creates the problem of the confirmation message. I think that we can stay with a clean writing of example notebooks, using the approach you mentioned to fix them.

In fact, the `&lt` is required for valid HTML, although most parsers will just pass a lone `<` verbatim.  Use of white space and attribute order is indeed done for canonicalization and thus detecting change.   Currently normalizing attribute order also discards user attributes.  They are not anticipated, but it should be fairly trivial to change the code to preserve them.

This discussion does suggest one enhancement: instead of storing the input document as the _unmodified version_, use a getValue() on it and use that as unchanged version.  That should deal with false change warnings.  Of course, if you do save, you still get the canonical version.  Would that make sense?

**Comment by friguzzi** [comment]
I think the change you propose makes perfect sense

**Comment by JanWielemaker** [comment]
Should be fixed with 4bd3c53254306c27665d8132cab51dfcdeda38c2
