### ISSUE TITLE
Allow a mechanism to see all the notebooks owned by a user.

### ISSUE THREAD

**Issue by samwalrus** [SWI-Prolog/swish#69]
At the moment when I am logged in I can only see the recent notebooks I have opened. If I forget the url to a notebook then I have no way of finding it in the future once it is not in my recent list. 

Therefore it would be good to have a mechanism to see all the notebooks owned by a myself and possibly even other users.

**Comment by JanWielemaker** [comment]
Opening a new tab now provides extensive search.
