### ISSUE TITLE
Can't update scripts saved with "Can save new version: only me"

### ISSUE THREAD

**Issue by balefrost** [SWI-Prolog/swish#73]
This was found on swish.swi-prolog.org; I'm not hosting my own server.

I created a script and saved it. In the "can save new version" area, I had only checked the "only me" checkbox. I was logged-in at the time, though I had just created an account. https://swish.swi-prolog.org/p/koSQyPSl.pl

Now, I can't update the script. When I try, I get "Permission denied. Please try a different name". If I look at the network inspector, I see that the server is sending back a 403 with an HTML - not JSON - error response.

I forked that document and this time saved it with both "can save new version: logged-in users, only me" checked. I'm now able to update this script just fine. https://swish.swi-prolog.org/p/jMIcMJce.pl

It seems like Swish isn't recognizing me as the owner of the first script.

**Comment by JanWielemaker** [comment]
This issue is fixed in recent versions.

**Comment by cjallen88** [comment]
I'm seeing this issue, I get a 403 JSON response on saving when only 'only 
me' is checked.

Logged in via google, on page:
https://swish.swi-prolog.org/p/Rosalind%20Challenges%202.swinb
