### ISSUE TITLE
Wrong link to Github in beware.html

### ISSUE THREAD

**Issue by MisterDev** [SWI-Prolog/swish#74]
`<a href="https:github.com/SWI-Prolog/swish.git">GitHub</a>`

[This](https://github.com/SWI-Prolog/swish/blob/master/web/help/beware.html#L79) `href` is translated to a wrong URL:

![screen shot 2017-08-09 at 11 42 27](https://user-images.githubusercontent.com/11232797/29115557-5b52227c-7cf8-11e7-9ddc-40fc65929b50.png)

**Comment by JanWielemaker** [comment]
Thanks.  Fixed.
