### ISSUE TITLE
Cliopatria does not like smpt:port setting ****

### ISSUE THREAD

**Issue by jrvosse** [SWI-Prolog/swish#75]
Jan,

When I load swish, I cannot change any settings in the cliopatria http interface because it complains about the smtp port settings: Wrong value for smtp:port: ****
I just checked and saw that config-available/email.pl om swish indeed sets this value:

:- set_setting_default(smtp:port,        ****).

Is this intentional?

Jacco

**Comment by JanWielemaker** [comment]
On 09/04/2017 02:59 PM, Jacco van Ossenbruggen wrote:
> Jan,
> 
> When I load swish, I cannot change any settings in the cliopatria http 
> interface because it complains about the smtp port settings: Wrong value 
> for smtp:port: ****
> I just checked and saw that config-available/email.pl om swish indeed 
> sets this value:
> 
> :- set_setting_default(smtp:port, ****).
> 
> Is this intentional?

In the SWISH case it is supposed to be something you must edit. 
Possibly using 25 is more appropriate.  At least that is valid, although 
this insecure default is not used a lot these days :)  Does that work?

	--- Jan

**Comment by jrvosse** [comment]
Yes, 25 works. Pushed to the cliopatria/swish repo, not here. 
https://github.com/ClioPatria/swish/commit/037d4a071d4bceca676bbae772bd055f523455c1
