### ISSUE TITLE
Server only serves localhost

### ISSUE THREAD

**Issue by Anniepoo** [SWI-Prolog/swish#77]
Per documentation 

% Using `localhost:Port`, we only bind to localhost interface!
% Use plain `3050` (or any port number you like) to make the server
% accessible from all network interfaces.

But actually does

run_swish :-
    set_prolog_flag(toplevel_goal, prolog), % run interactively
    current_prolog_flag(argv, Argv),
    argv_options(Argv, _, Options),
    option(port(Port), Options, 3050),
    server(localhost:Port).   <-- always forces localhost only

So how is one to start the server so it's accessible other than from localhost?

**Comment by JanWielemaker** [comment]
If you want anything complicated use the `daemon.pl` script.  That provides zillions of options.  In your case this probably does what you want:

    swipl daemon.pl --port=3050 --interactive

**Comment by Anniepoo** [comment]
thanks.

My fault, inspected daemon.pl but didn't figure out it was passing relevant options down.

**Comment by JanWielemaker** [comment]
Closing
