### ISSUE TITLE
rdf_global_id requires login while it should be sandboxed

### ISSUE THREAD

**Issue by jrvosse** [SWI-Prolog/swish#80]
In an anonymous swish session, the query

rdf_global_id(rdfs:label, L).

does not work:

No permission to call sandboxed `'$flushed_predicate'(_1226:'rdf prefix'(_1232,_1234))'
Reachable from:
	  rdf_prefixes:rdf_current_prefix(A,B:C,D)
	  rdf_prefixes:rdf_current_prefix(A:B,C)
	  rdf_prefixes:global(A,B,C,D)
	  rdf_prefixes:rdf_global_id(rdfs:label,A,B)
	  rdf_global_id(rdfs:label,A)
	  swish_trace:swish_call(rdf_global_id(rdfs:label,A))
	  '$swish wrapper'(rdf_global_id(rdfs:label,A),B)

**Comment by JanWielemaker** [comment]
Fixed in the latest SWI-Prolog git (Feb 20, 2018).
