### ISSUE TITLE
Losing var binding due to cell refresh

### ISSUE THREAD

**Issue by grsjst** [SWI-Prolog/swish#82]
Hello,

Please have a look at the following notebook: https://swish.swi-prolog.org/p/html-cell-test.swinb# that demonstrates the issue.

My html cell uses dropdown buttons to set the parameters of a query that produces a chart (using the c3 renderer). The resulting graph doesn't fit the visible window. When using the scroll-bar, this causes the cell to redraw but it has lost  the variable bindings that has been previously set.

thanks,
joost

**Comment by friguzzi** [comment]
Does not reproduce on MacOs + Chrome

**Comment by grsjst** [comment]
thanks for reporting Fabrizio

I am on Windows and Chrome, and it also happens on ubuntu + firefox (via vmware). 

For the error to happen, make sure the chart doesn't fit the window

**Comment by grsjst** [comment]
this issue seems to have resolved itself in the 20 feb 2018 version of swish
