### ISSUE TITLE
"bad request" bug?

### ISSUE THREAD

**Issue by seteahconnoc** [SWI-Prolog/swish#83]
Hello. Thanks for: swish.swi-prolog.org As a CS teacher, I appreciate it very much. Today, my students got a "bad request" output as an answer to obviously correct simple requests. After a while, it was working perfectly again. How can I prevent this bug in the future?

**Comment by JanWielemaker** [comment]
I don't know.  "bad request" isn't something you get from an invalid query AFAIK.  If you could give me details such as the client browser version, time and IP address I can examine the logs and see whether I can make sense out of it.  Is there an HTTP proxy in between?

Glad you like the service!

**Comment by seteahconnoc** [comment]
Please, excuse my rather vague description. Hopefully (?), the error will return, so I can post the exact Prolog output.

I expected some kind of misbehavior caused by too many queries from the same IP address - or something similar. My students were working vom 16 stations. Since you didn 't recognize the behavior so far, I can exclude this.

**Comment by JanWielemaker** [comment]
Hard to say.  If it happens, please include the message, time and IP address.  16 users shouldn't be a big deal.  It frequently peaks around 300 users and seems to handle that ok.

**Comment by JanWielemaker** [comment]
Something might be changed in the latest version.    A bug has been fixed for if the user executes a notebook query again before any reaction from the previous one, i.e., on _double click_ of the cell play button.   Not sure this is related or not.

**Comment by JanWielemaker** [comment]
As far as I recall this was a timing issue that has been resolved.  Closing.
