### ISSUE TITLE
daemon --help loads RDF-store first

### ISSUE THREAD

**Issue by jrvosse** [SWI-Prolog/swish#85]
Hi Jan,

./daemon.pl --help
% Restoring 20 snapshots using 20 concurrent workers

SWISH daemon first spends quite some time loading my big RDF-store, than prints the help message and quits... Should it not skip all initialization when --help is given as a startup option?

Jacco

**Comment by JanWielemaker** [comment]
Should be fixed with 02fe5df7b1e59ad8f064766f4480b5e0c84cd6bf
