### ISSUE TITLE
Example of how to handle I/O in a notebook

### ISSUE THREAD

**Issue by torbjornlager** [SWI-Prolog/swish#89]
The DCG example at [https://swish.swi-prolog.org/example/htmlcell.swinb](https://swish.swi-prolog.org/example/htmlcell.swinb) doesn't need to handle I/O, and (to me at least) it isn't clear how you would do it.

Perhaps an additional example could be based on the expert system code? Maybe a GUI with a textarea where the rules and the askables can be edited + a field for system output + two buttons (Yes and No) for user's input?

**Comment by torbjornlager** [comment]
Ok, but how do I get hold of the return value of the `new Pengine()` call, needed for the handling of user's responses? Compare with the old Scratchpad example at

[http://pengines.swi-prolog.org/apps/scratchpad/index.html#7ee7e85a-909f-11e8-8306-00163e8fc784.html](http://pengines.swi-prolog.org/apps/scratchpad/index.html#7ee7e85a-909f-11e8-8306-00163e8fc784.html)

**Comment by torbjornlager** [comment]
Ah, OK, I thought I tried it, but made a silly variable naming mistake. It's all clear now

Thanks!

**Comment by torbjornlager** [comment]
Hm, I've more or less just ported the old Scratchpad example from http://pengines.swi-prolog.org/apps/scratchpad/index.html#7ee7e85a-909f-11e8-8306-00163e8fc784.html, using `notebook.swish()` as you advised, but it looks like something is wrong. If you click the Yes button through the whole interaction, there should be two solutions, i.e. "Yes!" should be written twice. But the success handler is only triggered for the last success. See: [https://swish.swi-prolog.org/p/tweety.swinb](https://swish.swi-prolog.org/p/tweety.swinb)

**Comment by JanWielemaker** [comment]
Why?  I don't see you asking `next` to the Pengine?

**Comment by torbjornlager** [comment]
Sorry, I could have been clearer. If you click Yes three times in a row, the call to prove/1 succeeds by virtue of the first clause for good_pet/1. This should trigger the success handler and "Yes!" should be displayed and the Next button be activated. But for some reason the success handler isn't triggered. 

For comparison, the correct behaviour can be seen here: [http://pengines.swi-prolog.org/apps/scratchpad/index.html#7ee7e85a-909f-11e8-8306-00163e8fc784.html](http://pengines.swi-prolog.org/apps/scratchpad/index.html#7ee7e85a-909f-11e8-8306-00163e8fc784.html)

**Comment by torbjornlager** [comment]
Ok, problem solved! It turns out that `notebook.swish()` sets the `chunk` option of  `new Pengine()` to 5, which isn't what we want when dealing with a program that does I/O. Explicitly setting `chunk` to 1 gives the correct behaviour. See: [https://swish.swi-prolog.org/p/tweety.swinb](https://swish.swi-prolog.org/p/tweety.swinb).

In my opinion, the default of `chunk` for `notebook.swish()` either needs to change to 1, or the "new" default be documented.

**Comment by JanWielemaker** [comment]
Right.  For now I updated the documentation.
