### ISSUE TITLE
Feature request: loading files in SWISH

### ISSUE THREAD

**Issue by friguzzi** [SWI-Prolog/swish#92]
Loading files in swish could be useful: for .pl files, one can always copy and paste the code but for notebooks this is not possible and uploading them could be useful.
One could then write a notebook, download it, modify it locally and the upload it.

**Comment by JanWielemaker** [comment]
This is provided:

  - Create a notebook
  - Add a cell (+)
  - Select _more_
  - Use __Insert notebook from local file__

As it _inserts_ a notebook, this also allows you combine multiple notebooks into a single one.
